[package]
name = "olog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "loglib"
path = "src/lib.rs"

[dependencies]
clap = {version = "4.0.18", features = ["derive"]}
chrono = "0.4"
uuid = "1.2.1"